on:
  push:
    branches:
      - master
      - '*.*'
  pull_request: null

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      stability: >-
        ['prefer-stable', 'prefer-lowest']
